### ISSUE TITLE
Support Debian 10

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/packages.element.io#1]
`buster` is the new stable, so it would be good to have packages for it.

**Comment by jryans** [comment]
The [Riot package repo](https://packages.riot.im/debian/dists/buster/) supports `buster` and so does the [Matrix / Synapse repo](https://packages.matrix.org/debian/dists/buster/), so I think this is already happening?

**Comment by Half-Shot** [comment]
Ah, I guess Debian 9 and later would include 10. I was going to suggest updating the verbiage on https://riot.im/download/desktop/ but it's probably fine as is.
